In [63]:
import numpy as np 

`ndarray` - The default datatype in numpy

In [4]:
a = np.array([1, 2, 3])  # Create a rank 1 array - (rank refers to tensor rank. A matrix is a rank 2 tensor and so on..)
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [9]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)
print(b.shape,b.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3) 2


#### SLIDE 5

In [10]:
a = np.array([1,3,5,443,2,5,99])
print(a.shape,a.ndim,a.itemsize)

(7,) 1 4


#### SLIDE 6

In [11]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.T)
print(a.real)
print(a.imag)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
[[0 0 0]
 [0 0 0]]


In [12]:
b = np.sqrt([4, -1, -3J])
print(b)
print(b.real)
print(b.imag)

[2.        +0.j         0.        +1.j         1.22474487-1.22474487j]
[2.         0.         1.22474487]
[ 0.          1.         -1.22474487]


In [14]:
#flat
print(a)
for i in a:
    print(i)
for i in a.T:
    print(i)

[[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]
[1 4]
[2 5]
[3 6]


In [15]:
for i in a.flat:
    print(i)

1
2
3
4
5
6


In [16]:
# Shape
b = np.array([[1,2],[5,3],[9,1]])
print(b.shape)

(3, 2)


#### SLIDE 7

In [20]:
a = np.zeros((2,2,4,3))  # Create an array of all zeros
print(a)

[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]]


In [22]:
b = np.ones((3,2))   # Create an array of all ones
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [24]:
c = np.full((2,2), 7J) # Create a constant array
print(c)

[[0.+7.j 0.+7.j]
 [0.+7.j 0.+7.j]]


In [27]:
d = np.eye(4)        # Create a 2x2 identity matrix
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [28]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.72495506 0.58741051]
 [0.33681024 0.28823367]]


In [ ]:
a = np.array([1,4,6,3,1,5,7,8,5])
b = np.sort(a)
print(b)

#### SLIDE 8

In [35]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(b)
print(a)

[[2 3]
 [6 7]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

2
77


In [43]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)
row_r4 = a[1]
print(row_r4, row_r4.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)
[5 6 7 8] (4,)


In [44]:
print(row_r1, row_r2)
print(row_r1.T, row_r2.T)

[5 6 7 8] [[5 6 7 8]]
[5 6 7 8] [[5]
 [6]
 [7]
 [8]]


insert link to Andrew Ng's video

#### Slide 9

In [45]:
z = np.array([1, 2], dtype=np.int64) 
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(z)
print(y)

[1 2]
[[5. 6.]
 [7. 8.]]


#### SLIDE 10

Adding two arrays in C++
```c++

assert(u.size() == v.size()); // will fail with your initialization code, since
                              // your "result" has size 0, not size 10.
                              // perhaps do u.resize(v.size());
for (size_t i = 0; i < u.size(); ++i) {
    u[i] += v[i];
}

```

In [46]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)
print(x-y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[-4. -4.]
 [-4. -4.]]


In [47]:
#Addition
print(x+y)

[[ 6.  8.]
 [10. 12.]]


In [48]:
#Elementwise multiplication
print(x*y)

[[ 5. 12.]
 [21. 32.]]


In [52]:
# Division
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [49]:
#Matrix multiplication
print(y@x)

[[23. 34.]
 [31. 46.]]


In [50]:
# Dot Product
v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


In [51]:
# Square root
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
#SUM
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

#### SLIDE 11

In [54]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v


print(x)
print(y)
#Imagine y being a 10000x3 array - lots of time!

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [55]:
#better solution
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [56]:
y = x + vv  # Add x and vv elementwise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [58]:
#Broadcasting

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)
q = y+12
print(q)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[14 14 16]
 [17 17 19]
 [20 20 22]
 [23 23 25]]


#### Rules of broadcasting

The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

#### Vectorization

In [62]:
# Dot product 
import time 
import numpy 
import array 
  
# 8 bytes size int 
a = array.array('q') 
for i in range(1000000): 
    a.append(i)
    
b = array.array('q') 
for i in range(1000000, 2000000): 
    b.append(i) 
    
# classic dot product of vectors implementation  
tic = time.process_time() 
dot = 0.0; 
  
for i in range(len(a)): 
      dot += a[i] * b[i] 
        
toc = time.process_time() 
  
print("dot_product = "+ str(dot)); 
print("Computation time = " + str(1000*(toc - tic )) + "ms") 

n_tic = time.process_time() 
n_dot_product = numpy.dot(a, b) 
n_toc = time.process_time() 
  
print("\nn_dot_product = "+str(n_dot_product)) 
print("Computation time = "+str(1000*(n_toc - n_tic ))+"ms") 

dot_product = 8.333323333340204e+17
Computation time = 484.375ms

n_dot_product = 833332333333500000
Computation time = 0.0ms


### References
* Official numpy documentation - https://numpy.org/doc/1.18/numpy-ref.pdf
* More about packages and modules - https://www.geeksforgeeks.org/create-access-python-package/